services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./django.env
    depends_on:
      - pgdb

  pgdb:
    image: postgres:16
    env_file:
      - ./postgres.env
    container_name: pgdb
    ports:
      - 5433:5432
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata:
